### ISSUE TITLE
Nourishment effect texture on Hunger bar.

### ISSUE THREAD

**Issue by Food-dude-99** [TheGridExpert/VampiresDelight#10]
Hi Grid me again. I don't know if this is intentional or not when a non-vampire player gets the nourishment effect, the texture on their hunger bar is the gold blood drops instead of gold meat chunks. 

This is on a server with the latest versions of Vampire's Delight and Vampirism.

![Screenshot_20240528-174529_Discord](https://github.com/TheGridExpert/VampiresDelight/assets/152713993/a8243aef-4a5c-492f-99c3-b74057197ebb)

**Comment by TheGridExpert** [comment]
Fixed in 0.1.5
