### ISSUE TITLE
Render Thread Crash

### ISSUE THREAD

**Issue by Maxi90909** [TheGridExpert/VampiresDelight#12]
https://pastebin.com/9wP69rVi

I don't know. I spawned a boss from Box of horrors and then opened the creative menu. It then crashed and gave me this error report. Showing you mod.

**Comment by TheGridExpert** [comment]
The issue looks weird, but I'll look closer when I'm back, I'm not home for now. Thank you for reporting it

**Comment by TheGridExpert** [comment]
Could you please try 0.1.6 version of the mod and look if the issue is fixed, I made some changed in classes mentioned in report
