### ISSUE TITLE
silver knife's recipe is missing

### ISSUE THREAD

**Issue by tf2piro** [TheGridExpert/VampiresDelight#19]
Minecraft version
1.21.1
neoforge version
21.1.49
vampire's delight version
0.1.8
![2024-09-12_11 33 44](https://github.com/user-attachments/assets/808c855b-18e5-4336-8c17-edf39859ebc1)

**Comment by TheGridExpert** [comment]
Try the 0.1.9 version which was released today. This bug was fixed in this version

**Comment by tf2piro** [comment]
thx,it worked.

**Comment by TheGridExpert** [comment]
Ok, nice
