### ISSUE TITLE
Placing Cursed Spruce Cabinet results in crash (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by gamerpotion** [TheGridExpert/VampiresDelight#21]
Hi, using mod on NF 1.21.1 and testing on a server, placing down a cursed spruce cabinet makes it crash

tested on my modpack Vagrant Saga - https://www.curseforge.com/minecraft/modpacks/vagrant-saga

Crashlog - https://pastebin.com/Pf92Rj2v

**Comment by TheGridExpert** [comment]
[VampiresDelight-1.21.1-0.1.10-beta.1.jar.zip](https://github.com/user-attachments/files/17687169/VampiresDelight-1.21.1-0.1.10-beta.1.jar.zip)
Hello. Thanks for reporting it. I've fixed this, here's a beta version with this bug fixed. Could you please check if it works with your modpack now?

**Comment by TheGridExpert** [comment]
Fixed in 0.1.10
