### ISSUE TITLE
Server won't start with newest update

### ISSUE THREAD

**Issue by Ciellix** [TheGridExpert/VampiresDelight#22]
Updating Vampires Delight too the 0.1.10 on neoforge wont let it start up server logs below
https://mclo.gs/GE4i24f
Modpack https://legacy.curseforge.com/minecraft/modpacks/edge-of-chaos

**Comment by TheGridExpert** [comment]
Fixed in 0.1.10b

**Comment by Ciellix** [comment]
okay thanks
