### ISSUE TITLE
1.20.1 Disconnect From Server

### ISSUE THREAD

**Issue by Xaeive** [TheGridExpert/VampiresDelight#5]
MC Version [ 1.20.1 ]
Forge Version [ 47.2.20 ]
Modlist: [ [Modlist](https://pastebin.com/fLizTmS0) ]

Crash snippet:
```
[02Apr2024 21:20:20.192] [Render thread/DEBUG] [mixin/]: Mixing accessor.BloodStatsAccessor from vampiresdelight.mixins.json into de.teamlapen.vampirism.entity.player.vampire.BloodStats
[02Apr2024 21:20:20.204] [Netty Client IO #3/WARN] [com.connectivity.Connectivity/]: Packet not registered: ClientboundDisconnectPacket
[02Apr2024 21:20:20.206] [Netty Client IO #3/WARN] [com.connectivity.Connectivity/]: Packet:ClientboundDisconnectPacket 
[02Apr2024 21:20:20.230] [Netty Client IO #3/WARN] [com.connectivity.Connectivity/]: Packet data:
{
  "f_132075_": "translation{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag]}"
}
```

**Comment by TheGridExpert** [comment]
This issue has nothing to do with Vampire's Delight. The problem is in Connectivity mod, as far as I see. I recommend to report the issue to Connectivity's Github.

**Comment by 0xC0ncord** [comment]
I'm seeing the exact same error when joining a server without Connectivity installed.

**Comment by TheGridExpert** [comment]
The same? That's weird. I'll look at it more closely, hope to find something. I did try the mod on server, and searching the error didn't give much information so I supposed that's about Connectivity.

**Comment by TheGridExpert** [comment]
Does deleting Vampire's Delight solve the issue?

**Comment by 0xC0ncord** [comment]
> Does deleting Vampire's Delight solve the issue?

In my case it did. For what it's worth I had Vampire's Delight included in a modpack I built from scratch. If there is an incompatibility then I'm not sure which mod wasn't playing along as both the client and server logs had no real information about what might be causing the issue.

Let me see if I can create a reliable reproducer.

**Comment by Xaeive** [comment]
> In my case it did. For what it's worth I had Vampire's Delight included in a modpack I built from scratch. If there is an incompatibility then I'm not sure which mod wasn't playing along as both the client and server logs had no real information about what might be causing the issue.

Same here. I made my modpack myself and removing Vampire's Delight solves the issue. I can send the whole [debug.log](https://drive.google.com/file/d/19pZdX3rMELWsmMH_zPBj_oLX3RPNt7Cq/view?usp=sharing) if that will help. Warning, the log is long. The snippet i sent above is on line(32924)

**Comment by Xaeive** [comment]
I found the log for the dedicated server i was running at the time. I found this snippet. Not sure if it is helpful or not.

`[02Apr2024 21:17:06.049] [main/WARN] [mixin/]: @Mixin target de.teamlapen.vampirism.client.renderer.RenderHandler was not found vampiresdelight.mixins.json:MixinRenderHandler`

**Comment by TheGridExpert** [comment]
[VampiresDelight-0.1.1-build1-1.20.1.jar.zip](https://github.com/TheGridExpert/VampiresDelight/files/14908019/VampiresDelight-0.1.1-build1-1.20.1.jar.zip)
Could you please check if this build solve the issue you had?

**Comment by Xaeive** [comment]
> [VampiresDelight-0.1.1-build1-1.20.1.jar.zip](https://github.com/TheGridExpert/VampiresDelight/files/14908019/VampiresDelight-0.1.1-build1-1.20.1.jar.zip) Could you please check if this build solve the issue you had?

Yes! That version of the mod solved the issue!

**Comment by TheGridExpert** [comment]
It turned out that the problem was fixed just after the release of 0.1.0 by Cheaterpaul, but I didn't understand that it's about this exact issue. Glad it works.

**Comment by Poopooracoocoo** [comment]
Commit is https://github.com/TheGridExpert/VampiresDelight/commit/7520002e7a3bcc9dffc00e80637365c5827d9ba2

**Comment by TheGridExpert** [comment]
> Commit is [7520002](https://github.com/TheGridExpert/VampiresDelight/commit/7520002e7a3bcc9dffc00e80637365c5827d9ba2)

?

**Comment by Poopooracoocoo** [comment]
Apologies for the necropost! Just put that there for anyone else who was searching and wanted to know how this was fixed without digging thru the commits :)
