### ISSUE TITLE
Minecraft crashing on Launch

### ISSUE THREAD

**Issue by Food-dude-99** [TheGridExpert/VampiresDelight#8]
Hello Grid, I just updated Vampire's Delight to its latest version for Minecraft version 1.20.1.  The only mods on are the latest version of the dependencies. The crash report is the file attached.
[crash-2024-05-17_18.35.29-client.txt](https://github.com/TheGridExpert/VampiresDelight/files/15358831/crash-2024-05-17_18.35.29-client.txt)

**Comment by Mi6kbuttface** [comment]
Im also experiencing crashing on the new version

**Comment by TheGridExpert** [comment]
The crash report looks really weird, I'll try to recreate this and find the cause. Thank you for reporting it.

**Comment by TheGridExpert** [comment]
The problem turned out to be more simple than I thought. I've already uploaded a fix to Modrinth, and on CurseForge it's under review.
