### ISSUE TITLE
Alchemical Cocktail Server Issues

### ISSUE THREAD

**Issue by Food-dude-99** [TheGridExpert/VampiresDelight#9]
Hello Grid, While testing things out for a server, me and a friend discovered that the fire produced by the alchemical cocktail is:
A. The fire texture is client-sided by that I mean only the person who threw it sees the fire, but it still burns players and mobs.
B. The cocktail only spawns fire if it hits a mob/entity
C. Running and throwing the cocktail spawns fire at the player's feet. However, this fire isn't real and goes away by clicking it.
This is on a server with the latest version of Vampire's Delight and Vampirism. See pictures as some evidence.
![vampires delight](https://github.com/TheGridExpert/VampiresDelight/assets/152713993/b54dfe40-a52f-470e-a530-29383f2c7efa)
![Screenshot_20240528-174242_Discord](https://github.com/TheGridExpert/VampiresDelight/assets/152713993/16e00e5a-7670-40a4-bb22-ff7c09176504)

**Comment by Food-dude-99** [comment]
Ok I did some more testing and I learned that when you have configured and change the config for the alchemical cocktail to not burn the ground on client side it prevents you from seeing it all together.

**Comment by TheGridExpert** [comment]
[VampiresDelight-0.1.5-1.20.1.jar.zip](https://github.com/TheGridExpert/VampiresDelight/files/15485515/VampiresDelight-0.1.5-1.20.1.jar.zip)
Could you please check if this version works? I made some corrections which should fix it, but I can't recreate the conditions.

**Comment by Food-dude-99** [comment]
Adding this version works for loading client albeit slower than usual and for my server it cause it to crash. Mainly due not being able to load farmer's delight and along with any addons to the mod.

 Forge: net.minecraftforge:47.2.0[17:13:39] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Farmer's Delight (farmersdelight) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null,
        Vampire's Delight (vampiresdelight) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null,
        Delightful (delightful) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null 

Here is the crash report:
https://mclo.gs/ANJ4dAQ

**Comment by TheGridExpert** [comment]
[VampiresDelight-0.1.5-1.20.1.jar.zip](https://github.com/TheGridExpert/VampiresDelight/files/15489556/VampiresDelight-0.1.5-1.20.1.jar.zip)
I looked through the crush, and I think I understood what was the problem. This version should load, I think

**Comment by Food-dude-99** [comment]
Ok it works great it loads on the server and the cocktail works perfectly. I should note I did get these warnings as seen in the picture when restarting the server..
![warning](https://github.com/TheGridExpert/VampiresDelight/assets/152713993/2baffcfd-c8da-4340-88e2-af1439f9c77e)

**Comment by TheGridExpert** [comment]
Looks weird. Does it happen with all the items or just the exact ones? I googled and it looks like it's about switching version, but I am not sure about it

**Comment by Food-dude-99** [comment]
I restarted again and they didn't pop up looks like you are right.

**Comment by Food-dude-99** [comment]
Also I noticed the nourishment effect texture is also fixed.

**Comment by TheGridExpert** [comment]
Nice. Have you tried nourishing effect? I fixed it as well in this build.

**Comment by Food-dude-99** [comment]
I'm guessing I sent my previous comment too quickly for you to see lol.

**Comment by Food-dude-99** [comment]
If you didn't see I said yes it is fixed lol.

**Comment by TheGridExpert** [comment]
Sorry, weird, I think I'm either blind or this comment just didn't load when I was typing mine /:
